// Auth Action
export const SET_ARTIST_PROFILE = "SET_ARTIST_PROFILE";
export const SET_ARTIST_EMAIL = "SET_ARTIST_EMAIL";
export const SET_ARTIST_UID = "SET_ARTIST_UID";
export const SET_ISAUTHENTICATED = "SET_ISAUTHENTICATED";
export const SET_IS_EMAIL_VERIFIED = "SET_IS_EMAIL_VERIFIED";

// Uplaod Art Action
export const SET_ART_CATEGORY = "SET_ART_CATEGORY";
export const ADD_ART_TAG = "ADD_ART_TAG";
export const SET_ART_DOWNLOAD_URL = "SET_ART_DOWNLOAD_URL";
export const SET_ART_IMAGE_URL = "SET_ART_IMAGE_URL";
export const SET_ART_IMAGE_NAME = "SET_ART_IMAGE_NAME";

// artist update profile
export const SET_ARTIST_DATE_OF_BIRTH = "SET_ARTIST_DATE_OF_BIRTH";
export const SET_ARTIST_DATE_STARTED = "SET_ARTIST_DATE_STARTED";
export const SET_ARTIST_PROFILE_PIC_URL = "SET_ARTIST_PROFILE_PIC_URL";
export const SET_ARTIST_BIO = "SET_ARTIST_BIO";
export const SET_ARTIST_NAME = "SET_ARTIST_NAME";
export const SET_ARTIST_SOCIAL_LINK = "SET_ARTIST_SOCIAL_LINK";
export const SET_ARTIST_SOCIAL_PROVIDER_NAME =
  "SET_ARTIST_SOCIAL_PROVIDER_NAME";
export const SET_ARTIST_SOCIAL_ID = "SET_ARTIST_SOCIAL_ID";
export const ADD_ARTIST_SOCIAL = "ADD_ARTIST_SOCIAL";
