// Auth Action
export const SET_ARTIST_PROFILE = "SET_ARTIST_PROFILE";
export const SET_ARTIST_EMAIL = "SET_ARTIST_EMAIL";
export const SET_ARTIST_UID = "SET_ARTIST_UID";
export const SET_ISAUTHENTICATED = "SET_ISAUTHENTICATED";
export const SET_IS_EMAIL_VERIFIED = "SET_IS_EMAIL_VERIFIED";

// Uplaod Art Action
export const ADD_ART_TAG = "ADD_ART_TAG";
export const DELETE_ART_TAG = "DELETE_ART_TAG";
export const CLEAR_UPDATE_ART_STATE = "CLEAR_UPDATE_ART_STATE";
export const REMOVE_ART_FROM_ARTLIST = "REMOVE_ART_FROM_ARTLIST";
export const SET_ART_CATEGORY = "SET_ART_CATEGORY";
export const SET_ART_DOWNLOAD_URL = "SET_ART_DOWNLOAD_URL";
export const SET_ART_ID = "SET_ART_ID";
export const SET_ART_IMAGE_URL = "SET_ART_IMAGE_URL";
export const SET_ART_NAME = "SET_ART_NAME";
export const SET_ART_LIST = "SET_ART_LIST";
export const SET_ART_DESCRIPATION = "SET_ART_DESCRIPATION";
export const SET_STATE_TO_UPDATE_ART = "SET_STATE_TO_UPDATE_ART";

// artist update profile
export const ADD_ARTIST_SOCIAL = "ADD_ARTIST_SOCIAL";
export const CLEAR_UPDATE_ARTIST_PROFILE_STATE =
  "CLEAR_UPDATE_ARTIST_PROFILE_STATE";
export const DELETE_ARTIST_SOCIAL = "DELETE_ARTIST_SOCIAL";
export const SET_ARTIST_DATE_OF_BIRTH = "SET_ARTIST_DATE_OF_BIRTH";
export const SET_ARTIST_DATE_STARTED = "SET_ARTIST_DATE_STARTED";
export const SET_ARTIST_PROFILE_PIC_URL = "SET_ARTIST_PROFILE_PIC_URL";
export const SET_ARTIST_PROFILE_UPDATE_DATA = "SET_ARTIST_PROFILE_UPDATE_DATA";
export const SET_ARTIST_BIO = "SET_ARTIST_BIO";
export const SET_ARTIST_NAME = "SET_ARTIST_NAME";
export const SET_ARTIST_SOCIAL_LINK = "SET_ARTIST_SOCIAL_LINK";
export const SET_ARTIST_SOCIAL_PROVIDER_NAME =
  "SET_ARTIST_SOCIAL_PROVIDER_NAME";
export const SET_ARTIST_SOCIAL_ID = "SET_ARTIST_SOCIAL_ID";
